import { ArrowLeft, FileText } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";

export default function Terms() {
  const [, navigate] = useLocation();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <Button variant="ghost" size="sm" onClick={() => navigate("/")} className="mb-6">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>

        <div className="flex items-center gap-3 mb-8">
          <FileText className="w-6 h-6 text-primary" />
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        </div>

        <p className="text-sm text-muted-foreground mb-8">Last updated: February 2026</p>

        <div className="prose prose-sm max-w-none space-y-6 text-foreground">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By accessing or using AXIOM, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AXIOM is an AI-powered pre-submission manuscript audit tool. It analyzes academic manuscripts against reporting guidelines and publication standards. AXIOM provides feedback and suggestions but does not guarantee publication acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. User Responsibilities</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You are responsible for the content you upload. You represent that you have the right to submit any manuscript you upload for analysis. You agree not to upload content that infringes on intellectual property rights, contains malware, or violates applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. Intellectual Property</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You retain full ownership of your manuscripts and any content you upload. AXIOM does not claim any intellectual property rights over your uploaded content. Audit reports and feedback generated by AXIOM are provided for your personal academic use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Limitations</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AXIOM is a validation and feedback tool. It does not replace peer review, editorial judgment, or expert mentorship. Audit scores and suggestions are AI-generated and should be used as one input in your revision process. AXIOM is not a co-author and does not generate manuscript content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Disclaimer of Warranties</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AXIOM is provided "as is" without warranties of any kind. We do not guarantee that audit feedback will be error-free, complete, or that following our suggestions will result in publication acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, AXIOM shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to manuscript rejection, publication delays, or data loss.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Account Termination</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You may delete your account and all associated data at any time. We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">9. Changes to Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may modify these Terms of Service at any time. Continued use of AXIOM after changes constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
